### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of null

### ISSUE THREAD

**Issue by christophergandrud** [andrewrynhard/atom-latex-plus#11]
[Enter steps to reproduce below:]

Tried to compile simple .tex document

**Atom Version**: 0.200.0
**System**: Mac OS X 10.10.3
**Thrown From**: [texlicious](https://github.com/arynhard/atom-texlicious) package, v0.4.1
### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of null

```
At /Users/christophergandrud/.atom/packages/texlicious/lib/main.coffee:190

TypeError: Cannot read property 'getPath' of null
  at TeXlicious.makeArgs (/Users/christophergandrud/.atom/packages/texlicious/lib/main.coffee:190:43)
  at TeXlicious.compile (/Users/christophergandrud/.atom/packages/texlicious/lib/main.coffee:235:13)
  at atom-text-editor.atom.commands.add.texlicious:compile (/Users/christophergandrud/.atom/packages/texlicious/lib/main.coffee:92:10)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```
### Commands

```
     -1:11.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:40.6.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:40 core:backspace (atom-text-editor.editor.is-focused)
     -0:36.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:30.7.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:29.8.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:18.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:14.6.0 core:delete (atom-text-editor.editor.is-focused)
     -0:14.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:12.6.0 core:delete (atom-text-editor.editor.is-focused)
     -0:12.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:06.0 core:delete (atom-text-editor.editor.is-focused)
     -0:05.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:03.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:00.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.7.0 texlicious:compile (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-light-syntax"
    ],
    "audioBeep": false
  },
  "texlicious": {}
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.27.4
atom-lint, v0.20.1
autoclose-html, v0.16.0
autocomplete-bibtex, v0.5.7
autocomplete-paths, v1.0.2
fonts, v0.4.2
language-knitr, v0.2.0
language-latex, v0.6.1
language-pfm, v0.69.0
language-r, v0.2.0
language-stata, v0.1.0
red-wavy-underline, v0.3.0
tabs-to-spaces, v0.10.0
texlicious, v0.4.1
wordcount, v2.2.2

# Dev
No dev packages
```

**Comment by andrewrynhard** [comment]
@christophergandrud thank you for the report. This will be fixed in an upcoming push. Within the week.

**Comment by christophergandrud** [comment]
:+1:

**Comment by andrewrynhard** [comment]
@christophergandrud closing this. Pushing an update tonight.
