### ISSUE TITLE
Uncaught TypeError: Cannot read property 'join' of undefined

### ISSUE THREAD

**Issue by Quinch** [andrewrynhard/atom-latex-plus#14]
1. Open LaTeX file
2. Compile with Packages -> TeXlicious -> Compile

**Atom Version**: 1.0.0
**System**: Linux Mint
**Thrown From**: [texlicious](https://github.com/arynhard/atom-texlicious) package, v0.4.3
### Stack Trace

Uncaught TypeError: Cannot read property 'join' of undefined

```
At /home/chris/.atom/packages/texlicious/lib/latexmk.coffee:11

TypeError: Cannot read property 'join' of undefined
  at Latexmk.module.exports.Latexmk.make (/home/chris/.atom/packages/texlicious/lib/latexmk.coffee:11:30)
  at TeXlicious.compile (/home/chris/.atom/packages/texlicious/lib/main.coffee:174:21)
  at atom-text-editor.atom.commands.add.texlicious:compile (/home/chris/.atom/packages/texlicious/lib/main.coffee:77:10)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```
### Commands

```
  3x -1:49.5.0 texlicious:compile (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {},
  "texlicious": {
    "texFlavor": "xelatex",
    "bibtexEnabled": true
  }
}
```
### Installed Packages

``` coffee
# User
linter-chktex, v0.3.0
texlicious, v0.4.3

# Dev
No dev packages
```

**Comment by Quinch** [comment]
Noted that 'TeXlicious compiling...' was in the status bar at the bottom.  Closed atom and restarted and now can't replicate.

**Comment by andrewrynhard** [comment]
@Quinch: unfortunately I was unable to reproduce this. I will leave it open for a bit in case someone else faces an issue. It sounds like it has something to do with a problem outside of TeXlicious.

**Comment by Quinch** [comment]
@arynhard thanks for looking. It has successfully run once, but not again.  Just so that you have the info, in case it's of use:

file: test.tex

``` latex
\documentclass{article}
\begin{document}
\section{Sample Section}
Some sample text
\end{document}
```

latekmk version 4.35 runs successfully on the command line: `latexmk -xelatex -bibtex test`

After an attempt to run from Atom, the text 'TeXlicious: Compiling...' remains on the status bar.

If I can look anywhere else for logs, etc., happy to do that.

**Comment by andrewrynhard** [comment]
@Quinch: hmm. Do you get the `Uncaught TypeError: Cannot read property 'join' of undefined` error every time?

**Comment by Quinch** [comment]
@arynhard every time, except for just once.  The only successful run was't the first attempt. Updated to 0.4.4, and still the same.

**Comment by andrewrynhard** [comment]
@Quinch: I have pushed a version of TeXlicious to a branch called `develop`. Are you comfortable with cloning this repo, checking out the develop branch, and installing via apm?

**Comment by Quinch** [comment]
@arynhard Installed the develop branch and had a look at the console log:

```
'linter-chktex.chktexExecutablePath' could not set the default. Attempted default: undefined; Schema: {"default":null,"title":"chktex Executable Path","type":"string"}
/home/chris/.atom/packages/linter-chktex/lib/init.coffee:11 activate linter-chktex
index.js:56 Window load time: 1451ms
/home/chris/.atom/packages/texlicious/lib/latexmk.coffee:17 Uncaught TypeError: Cannot read property 'join' of undefined
```

**Comment by Quinch** [comment]
@arynhard In testing I also swapped between a couple of files, and sometimes when I change file and compile it starts compiling for all files - even those it failed on before.

**Comment by andrewrynhard** [comment]
@Quinch: this is very strange. I cannot reproduce this using linux mint. Would you be willing to go on an irc channel for more rapid debugging? I will try to resolve this as fast as I can.

**Comment by Quinch** [comment]
@arynhard happy to try.  I know very little coffeescript, but from some log calls it looks like `@getTexEditor` in `makeArgs` (in `main.coffee`) is `null` sometimes.  Because of that, `args` is undefined going into `make` (in `latexmk.coffee`).

**Comment by andrewrynhard** [comment]
@Quinch: that is what I am suspecting. I don't know why that is the case because I can't reproduce it. Anyways. If you want, you can email me your nickname on freenode and I could invite you to a private chat.

**Comment by andrewrynhard** [comment]
@Quinch: my email is on my profile.

**Comment by uliska** [comment]
I also get this error when compiling a MWE file. This is on LMDE (Linux Mint Debian Edition), freshly installed.

```
TypeError: Cannot read property 'join' of undefined
  at Latexmk.module.exports.Latexmk.make (/home/uliska/.atom/packages/texlicious/lib/latexmk.coffee:11:30)
  at TeXlicious.compile (/home/uliska/.atom/packages/texlicious/lib/main.coffee:174:21)
  at atom-text-editor.atom.commands.add.texlicious:compile (/home/uliska/.atom/packages/texlicious/lib/main.coffee:77:10)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:180:20)
```

**Comment by uliska** [comment]
(BTW: It's a cool feature that the error message in Atom links to this issue page)

**Comment by andrewrynhard** [comment]
@uliska: The workaround for now is to make sure to open the directory containing the tex file, as opposed to having just the file open.

**Comment by uliska** [comment]
Thank you, that seems to work so far.

**Comment by andrewrynhard** [comment]
@Quinch, @uliska : may I ask what steps you are taking to open the file? Any time I open a file with Atom the parent directory is opened as well. I would like to reproduce this so I can push a fix

**Comment by uliska** [comment]
I must admit I had a hard time to reproduce that (although it _did_ happen when I had tried out `TeXlicious` for the first time). But now I see how to open a file _without_ its folder:
- Open any file, so its folder is opened too
- Close that file: the folder remains open
- Open a `.tex` file from a different folder using `File->Open` (Ctrl+O)  
  => Folder from first file is still open

I admit this is a rare case, but nevertheless it produces that error condition.

**Comment by Quinch** [comment]
1 `File->New`
2 Edit `*.tex` file
3 `File->Save` and save outside the current project

**Comment by andrewrynhard** [comment]
@Quinch @uliska : The newest version should fix this issue. Please reopen if it does not.
