### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by TuringKi** [andrewrynhard/atom-latex-plus#23]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.9
**System**: Unknown Windows Version
**Thrown From**: [latex-plus](https://github.com/andrewrynhard/atom-latex-plus) package, v0.7.7
### Stack Trace

Uncaught TypeError: Cannot read property 'toString' of undefined

```
At /C:/Users/TuringKi/.atom/packages/latex-plus/lib/parser.js:38

TypeError: Cannot read property 'toString' of undefined
    at C:/Users/TuringKi/.atom/packages/latex-plus/lib/parser.js:17:28
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:302:5)
```
### Commands

```
     -0:24.2.0 latex-plus:compile (atom-text-editor.editor.is-focused)
     -0:19.6.0 editor:toggle-line-comments (ul.list-inline.tab-bar.inset-panel)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "disabledPackages": [
      "latex"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
language-latex, v0.6.1
language-matlab, v0.1.1
latex-plus, v0.7.7
minimap, v4.13.2

# Dev
No dev packages
```

**Comment by mredaelli** [comment]
I had the same error. In my case, I had not installed `latexmk` :)

**Comment by MatteoRagni** [comment]
1. write a beamer latex file 
2. try to compile

(with MikTex 2.9). `latexmk`installed and db refreshed.

**Atom Version**: 1.0.19
**System**: Microsoft Windows 10 Pro
**Thrown From**: [latex-plus](https://github.com/andrewrynhard/atom-latex-plus) package, v0.7.7

### Stack Trace

Uncaught TypeError: Cannot read property 'toString' of undefined

```
At /C:/Users/nirvana1289/.atom/packages/latex-plus/lib/parser.js:38

TypeError: Cannot read property 'toString' of undefined
  at ReadFileContext.callback (C:\Users\nirvana1289\.atom\packages\latex-plus\lib\parser.js:38:30)
  at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)

```

### Commands

```
     -3:13.4.0 latex-plus:edit (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -3:09.1.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -2:50 latex-plus:compile (atom-text-editor.editor.is-focused)
     -2:39.7.0 latex-plus:edit (atom-text-editor.editor.is-focused)
     -2:20.1.0 core:move-up (atom-text-editor.editor.is-focused)
  6x -2:19.9.0 core:move-left (atom-text-editor.editor.is-focused)
  4x -2:17.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:14.9.0 core:save (atom-text-editor.editor.is-focused)
  2x -2:01.4.0 latex-plus:compile (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "projectHome": "D:/workspace",
    "audioBeep": false
  }
}
```

### Installed Packages

``` coffee
# User
language-latex, v0.6.1
latex-plus, v0.7.7
minimap, v4.13.4
minimap-git-diff, v4.1.8
preview-inline, v0.4.4

# Dev
No dev packages
```

**Comment by MatteoRagni** [comment]
Now it is working. Problem with configurations (string with escaping not recognized, do not requires fixes)

**Comment by MatteoRagni** [comment]
[Enter steps to reproduce below:]
1. Edit a project to get project path == output path (using absolute coordinates)
2. Compile

**Atom Version**: 1.0.19
**System**: Microsoft Windows 10 Pro
**Thrown From**: [latex-plus](https://github.com/andrewrynhard/atom-latex-plus) package, v0.7.7

### Stack Trace

Uncaught TypeError: Cannot read property 'toString' of undefined

```
At /C:/Users/nirvana1289/.atom/packages/latex-plus/lib/parser.js:38

TypeError: Cannot read property 'toString' of undefined
  at ReadFileContext.callback (C:\Users\nirvana1289\.atom\packages\latex-plus\lib\parser.js:38:30)
  at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)

```

### Commands

```
     -9:40.9.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -9:40.2.0 core:save (atom-text-editor.editor.is-focused)
     -9:25.3.0 latex-plus:compile (atom-text-editor.editor.is-focused)
     -1:56 latex-plus:edit (atom-text-editor.editor.is-focused)
     -1:42.3.0 latex-plus:compile (atom-text-editor.editor.is-focused)
     -0:37.3.0 latex-plus:edit (atom-text-editor.editor.is-focused)
     -0:36.2.0 core:move-right (atom-text-editor.editor.is-focused)
  5x -0:34.6.0 core:move-down (atom-text-editor.editor.is-focused)
 13x -0:33.7.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:28.9.0 core:save (atom-text-editor.editor.is-focused)
  9x -0:23.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:18.3.0 core:copy (atom-text-editor.editor.is-focused)
  2x -0:16.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:16.6.0 core:paste (atom-text-editor.editor.is-focused)
     -0:16 core:save (atom-text-editor.editor.is-focused)
     -0:02.8.0 latex-plus:compile (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {
    "projectHome": "D:/workspace",
    "audioBeep": false,
    "disabledPackages": [
      "markdown-preview"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "latex-plus": {
    "bibtexEnabled": true,
    "texBin": "C:/Program Files/MiKTeX 2.9/miktex/bin/x64"
  }
}
```

### Installed Packages

``` coffee
# User
atom-material-syntax, v0.2.4
atom-material-ui, v0.6.2
language-latex, v0.6.1
latex-plus, v0.7.7
linter, v1.8.1
linter-chktex, v1.1.3
linter-ruby, v1.1.1
markdown-preview-plus, v2.2.0
mathjax-wrapper, v0.1.0
minimap, v4.13.4
minimap-git-diff, v4.1.8
pdf-view, v0.29.0
preview-inline, v0.4.4

# Dev
No dev packages
```

**Comment by Thorinori** [comment]
i have been attempting to compile, and keep getting this error. I made sure I have latexmk installed, and everything should be configured right I think? I am including the contents of the JSON file since that may be part of the issue.
JSON:
{
  "projectPath": "C:\Users\Thorinori\Desktop\testProject",
  "title": "LaTeX-Plus Project",
  "root": "main.tex",
  "program": "pdflatex",
  "output": ".latex"
}
\ is used as an escape sequence since it errors with just \
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Microsoft Windows 8.1
**Thrown From**: [latex-plus](https://github.com/andrewrynhard/atom-latex-plus) package, v0.7.8

### Stack Trace

Uncaught TypeError: Cannot read property 'toString' of undefined

```
At /C:/Users/Thorinori/.atom/packages/latex-plus/lib/parser.js:38

TypeError: Cannot read property 'toString' of undefined
  at ReadFileContext.callback (C:\Users\Thorinori\.atom\packages\latex-plus\lib\parser.js:38:30)
  at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)

```

### Commands

```
  2x -0:33.2.0 core:save (atom-text-editor.editor.is-focused)
  7x -0:30.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:27.4.0 core:save (atom-text-editor.editor.is-focused)
  8x -0:26.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:23.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:16.8.0 latex-plus:compile (atom-text-editor.editor.is-focused)
  7x -0:11.2.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:07.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:03.7.0 latex-plus:compile (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {
    "excludeVcsIgnoredPaths": false
  },
  "latex-plus": {
    "texBin": "C:\\texlive\\2015\\bin",
    "texInputs": "C:\\local\\bin"
  }
}
```

### Installed Packages

``` coffee
# User
language-latex, v0.6.1
latex, v0.28.2
latex-plus, v0.7.8
latexer, v0.2.7
preview-inline, v0.5.1

# Dev
No dev packages
```

**Comment by andrewrynhard** [comment]
@MatteoRagni @Thorinori: This seems like an issue when using windows. I do not have a windows machine handy at the moment. Are you able to reproduce this error on demand?

**Comment by elmewo** [comment]
Affects me as well in windows.
Doesn't matter if / or \\ is used in file path.

**Comment by andrewrynhard** [comment]
@elmewo:  Hmmm, ok. Let me try to get a windows machine going and debug this.

**Comment by Thorinori** [comment]
@andrewrynhard Whenever I attempt to compile it happens.

**Comment by MatteoRagni** [comment]
Confirm: on windows

**Comment by maecky** [comment]
Same here on windows 10 64Bit

**Comment by alex-friedl** [comment]
Problem occurs under MacOS X as well:

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.3
**System**: Mac OS X 10.11.2
**Thrown From**: [latex-plus](https://github.com/andrewrynhard/atom-latex-plus) package, v0.7.8

### Stack Trace

Uncaught TypeError: Cannot read property 'toString' of undefined

```
At /Users/alfriedl/.atom/packages/latex-plus/lib/parser.js:17

TypeError: Cannot read property 'toString' of undefined
    at ReadFileContext.callback (/Users/alfriedl/.atom/packages/latex-plus/lib/parser.js:17:28)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
```

### Commands

```
     -0:00.9.0 latex-plus:compile (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "latex-plus": {
    "texBin": "/Library/TeX/texbin"
  }
}
```

### Installed Packages

``` coffee
# User
.bin, vundefined
atom-typescript, v8.0.0
file-icons, v1.6.13
language-latex, v0.6.1
latex, v0.28.2
latex-plus, v0.7.8
linter, v1.11.3
linter-jshint, v1.2.2

# Dev
No dev packages
```

**Comment by dpo** [comment]
Same problem on OSX. @alex-friedl check that `/Library/TeX/texbin` is correct. On my installation of TeX-Live, it isn't. Using `/usr/texbin` appears to work.

**Comment by iagobaapellaniz** [comment]
Same here withe the very last version of atom, latex-plus and mac os x.

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [latex-plus](https://github.com/andrewrynhard/atom-latex-plus) package, v0.8.3

### Stack Trace

Uncaught TypeError: Cannot read property 'toString' of undefined

```
At /Users/iagoba/.atom/packages/latex-plus/lib/parser.js:17

TypeError: Cannot read property 'toString' of undefined
    at ReadFileContext.callback (/Users/iagoba/.atom/packages/latex-plus/lib/parser.js:17:28)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
```

### Commands

```
     -9:56.7.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  5x -9:55.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -9:50.4.0 core:save (atom-text-editor.editor.is-focused)
     -9:45.5.0 latex-plus:compile (atom-text-editor.editor.is-focused)
  2x -8:58.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -8:54.4.0 core:save (atom-text-editor.editor.is-focused)
     -8:11.8.0 terminal-plus:status-red (i.icon.icon-terminal)
     -8:07.7.0 terminal-plus:status-default (i.icon.icon-terminal)
     -5:52.4.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
     -4:54.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -4:54 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:54.5.0 tabs:split-left (li.tab.sortable.active.right-clicked)
     -0:38.6.0 tabs:split-right (li.tab.sortable.active.right-clicked)
     -0:35.8.0 tabs:split-left (li.tab.sortable.active.right-clicked)
     -0:02.0 latex-plus:compile (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {},
  "latex-plus": {
    "texBin": "/Library/TeX/texbin/"
  }
}
```

### Installed Packages

``` coffee
# User
bombe, v0.1.3
indent-detective, v0.1.0
ink, v0.3.2
julia-client, v0.3.1
language-latex, v0.6.1
latex, v0.29.0
latex-completions, v0.3.1
latex-plus, v0.8.3
minimap, v4.19.0
pdf-view, v0.39.0
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by andrewrynhard** [comment]
@iagoba has any compilation worked at all?

**Comment by iagobaapellaniz** [comment]
It fixed after installing latexmk. Could it be the reason? Now latex-plus works! Great!

**Comment by andrewrynhard** [comment]
@iagoba good to hear. This seems to be the answer to this issue as others have said the same.
