### ISSUE TITLE
Uncaught TypeError: Cannot read property 'edit' of undefined

### ISSUE THREAD

**Issue by ghost** [andrewrynhard/atom-latex-plus#28]
Hi, I just tried to define the project path. Recently, that worked without any issues.

[Enter steps to reproduce below:]
1. ...`cmd` -`'`
2. ...

**Atom Version**: 1.3.3
**System**: Mac OS X 10.8.5
**Thrown From**: [latex-plus](https://github.com/andrewrynhard/atom-latex-plus) package, v0.7.8
### Stack Trace

Uncaught TypeError: Cannot read property 'edit' of undefined

```
At /Users/evgenionegin/.atom/packages/latex-plus/lib/main.js:40

TypeError: Cannot read property 'edit' of undefined
    at atom-workspace.latexPlusEdit (/Users/evgenionegin/.atom/packages/latex-plus/lib/main.js:40:21)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -2:42.3.0 latex-plus:compile (atom-text-editor.editor.is-focused)
  4x -2:15.2.0 latex-plus:edit (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "linter-chktex",
      "linter-flake8",
      "metrics",
      "symbols-view"
    ]
  },
  "latex-plus": {
    "bibtexEnabled": true,
    "texBin": "/usr/texbin/"
  }
}
```
### Installed Packages

``` coffee
# User
atom-ctags, v4.4.2
atom-webbrowser, v2.1.4
auto-update-packages, v1.0.0
language-knitr, v0.2.0
language-latex, v0.6.1
language-pgsql, v0.2.0
language-r, v0.4.0
language-sql-mysql, v0.3.1
latex, v0.28.2
latex-plus, v0.7.8
latexer, v0.2.7
linter, v1.11.3
markdown-preview-plus, v2.2.2
open-recent, v4.0.1
pdf-view, v0.39.0
term3, v0.21.0

# Dev
No dev packages
```

**Comment by andrewrynhard** [comment]
Thank you for reporting this issue. Are you able to reproduce this error? If so what steps do you take to do so?

**Comment by dpo** [comment]
I suspect this might be related to one of my interrogations in #31. @hugeme does it work if you first compile your LaTeX document, and only after that hit  ⌘-`'`?
