### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by mbueti** [andrewrynhard/atom-latex-plus#3]
[Enter steps to reproduce below:]
1. Open .tex file
2. Run compile

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.2
**Thrown From**: [texlicious](https://github.com/arynhard/atom-texlicious) package, v0.2.7
### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At /Users/mbueti/.atom/packages/texlicious/lib/latexmk.coffee:11

TypeError: Cannot read property 'replace' of undefined
  at /Users/mbueti/.atom/packages/texlicious/lib/latexmk.coffee:11:24
  at Latexmk.module.exports.Latexmk.make (/Users/mbueti/.atom/packages/texlicious/lib/latexmk.coffee:24:9)
  at TeXlicious.compile (/Users/mbueti/.atom/packages/texlicious/lib/main.coffee:116:21)
  at atom-text-editor.atom.commands.add.texlicious:compile (/Users/mbueti/.atom/packages/texlicious/lib/main.coffee:60:33)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-space-pen-views/lib/select-list-view.js:335:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:170:20)

```
### Commands

```
     -7:12.8 command-palette:toggle (atom-text-editor.editor.is-focused)
     -7:07.4 editor:consolidate-selections (atom-text-editor.editor.mini)
     -7:07.4 core:cancel (atom-text-editor.editor.mini)
     -7:07.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -7:07.0 core:cancel (atom-text-editor.editor.is-focused)
     -1:38.5 texlicious:compile (atom-text-editor.editor.is-focused)
     -1:03.8 settings-view:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-smyck.theme-one-dark-ui)
     -0:19.7 core:paste (atom-text-editor#texlicious.texPath.editor.mini)
     -0:03.2 command-palette:toggle (atom-text-editor.editor.is-focused)
  3x -0:01.3 core:move-down (atom-text-editor.editor.mini)
     -0:00.5 core:confirm (atom-text-editor.editor.mini)
     -0:00.5 texlicious:compile (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "smyck"
    ]
  },
  "texlicious": {
    "program": "pdfLaTeX",
    "shellEscapeEnabled": true,
    "texPath": "/usr/texbin/"
  }
}
```
### Installed Packages

``` coffee
# User
cucumber, v0.4.1
file-icons, v1.4.8
language-haml, v0.15.0
language-latex, v0.4.1
latex, v0.18.0
minimap, v4.1.2
minimap-git-diff, v3.1.1
smyck, v0.1.0
texlicious, v0.2.7

# Dev
No dev packages
```

/cc @atom/core

**Comment by andrewrynhard** [comment]
@mbueti: Thank you for the report. Pushing a fix in about 10 minutes.

**Comment by mbueti** [comment]
Wonderful! Thank you for the fast turnaround on this, especially on a weekend!

**Comment by andrewrynhard** [comment]
@mbueti: Not a problem!
