### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received null

### ISSUE THREAD

**Issue by rodneyp290** [andrewrynhard/atom-latex-plus#69]
I keep getting the following error when I compile my LaTeX document, however it the latex document seem to compiled successfully. This below information was generated when I "Create isssue..." on the error pop-up 

**Atom Version**: 1.9.9
**System**: linux 4.7.1-1-ARCH
**Thrown From**: [latex-plus](https://github.com/andrewrynhard/atom-latex-plus) package, v0.8.7
### Stack Trace

Uncaught TypeError: Path must be a string. Received null

```
At path.js:7

TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.join (path.js:1253:7)
    at Object.getRootPath (/home/rodney/.atom/packages/latex-plus/lib/main.js:318:17)
    at /home/rodney/.atom/packages/latex-plus/lib/main.js:168:30
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /home/rodney/.atom/packages/latex-plus/lib/compiler.js:39:22
    at ChildProcess.exithandler (child_process.js:221:5)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)
```
### Commands

```
  2x -1:09.5.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -1:08.5.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
  8x -1:06.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:51.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:50.8.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:50.4.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:50.3.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:49.8.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:48.9.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:47.9.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:47.3.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:46.9.0 core:select-up (atom-text-editor.editor.is-focused)
     -0:45.8.0 core:cut (atom-text-editor.editor.is-focused)
     -0:45.4.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:44.7.0 core:paste (atom-text-editor.editor.is-focused)
     -0:01.3.0 latex-plus:compile (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "an-old-hope-syntax"
    ]
  },
  "latex-plus": {
    "ghostscriptBin": "/usr/bin/",
    "openOutputEnabled": false,
    "texBin": "/usr/bin/"
  }
}
```
### Installed Packages

``` coffee
# User
an-old-hope-syntax, v0.5.0 (active)
atom-html-preview, v0.1.22 (active)
language-latex, v0.6.1 (active)
latex-plus, v0.8.7 (active)
pdf-view, v0.50.0 (active)
react, v0.16.0 (active)
robin-hood-syntax, v1.0.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.1 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by i-apellaniz** [comment]
Mee too

**Comment by maaaaadn** [comment]
just started using atom and I've got exactly the same issue on ubuntu 16.04
have you found a solution yet?

**Comment by rodneyp290** [comment]
Uh I no longer get this error since an update, currently on 0.9.1. I probably should have closed the issue, are you sure it is the same error message?

**Comment by maaaaadn** [comment]
alright... 
yeah it was exactly the same issue, I compared line-to-line. Somehow now it works, did an update and reboot today in the morning, one of that helped...  :+1:

**Comment by rodneyp290** [comment]
Okay, probably should close this issue then
